config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
  validates :price_per_night, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.delete
    redirect_to root_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description,
                                 :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1 class="mt-3">Edit <%= @flat.name %></h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>All our Flats (<%= @flats.count %>)</h1>
  <ul>
    <% @flats.each do |flat| %>
      <li>
        <div class="card">
          <div class="card-body">
            <h2><%= flat.name %></h2>
            <h5><%= flat.address %></h3>
            <i class="fas fa-male"></i><h6><%= flat.number_of_guests %></h6>
            <i class="fas fa-pound-sign"></i><h6><%= flat.price_per_night %></h6>
          </div>
          <div class="card-footer">
            <%= link_to 'More Info', flat_path(flat) , class: "btn btn-outline-primary" %>
            <%= link_to 'Edit', edit_flat_path(flat) , class: "btn btn-outline-warning" %>
            <%= link_to 'Delete', flat_path(flat), class: "btn btn-outline-danger",
                                                   method: :delete,
                                                   data: { confirm: "Delete flat?"}  %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class="mt-3">Add a new flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container mt-3">
  <h1><%= @flat.name %></h1>
  <h5><%= @flat.address %></h3>

  <%= link_to 'Back', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4775c39bd5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark p-2">
      <%= link_to 'Simple AirBnB', root_path, class:"navbar-brand mx-4" %>
      <%= link_to 'Add new', new_flat_path, class: "btn btn-outline-primary mx-4" %>
    </nav>

    <%= yield %>
  </body>
</html>